version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  consumer:
    image: kafka-consumer:latest
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: "${KAFKA_SERVER:-kafka}"
      KAFKA_PORT: "${KAFKA_SERVER:-9092}"
      KAFKA_TOPIC: "${KAFKA_TOPIC:-test}"
      PRODUCER_HOST: "${PRODUCER_HOST:-producer}"
      PRODUCER_PORT: "${FLASK_PORT:-5000}"
      PRODUCER_MSG_ENDPOINT: "${PRODUCER_MSG_ENDPOINT:-messages}"
    tty: true
    stdin_open: true
  
  producer:
    image: kafka-producer:latest
    depends_on:
      - kafka
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"
    environment:
      KAFKA_SERVER: "${KAFKA_SERVER:-kafka}"
      KAFKA_PORT: "${KAFKA_SERVER:-9092}"
      KAFKA_TOPIC: "${KAFKA_TOPIC:-test}"
      FLASK_HOST: "${FLASK_HOST:-0.0.0.0}"
      FLASK_PORT: "${FLASK_PORT:-5000}"
    tty: true
    stdin_open: true
